### ISSUE TITLE
Can i modify translation object??

### ISSUE THREAD

**Issue by futureinapps** [rmdort/react-redux-multilingual#1]
use like this and if possible how can get string:
{
  en: {
    locale: 'en-US',
    messages: {
      sub1:{
          hello: 'how are you {name}',
      sub2:{
          hello: 'how are you {name}'
      }
      }
    }
  },
  zh: {
    locale: 'zh',
    messages: {
      hello: '你好！你好吗 {name}'
    }
  }
}

**Comment by rmdort** [comment]
I dont quite understand your question. This is the format of the translations object

```
{
  en: {
    locale: 'en-US',
    messages: {
      hello: 'how are you {name}'
    }
  },
  zh: {
    locale: 'zh',
    messages: {
      hello: '你好！你好吗 {name}'
    }
  }
}
```

We do support nested objects

```
{translate('sub1.hello', { name: 'John Doe' })}
```
