### ISSUE TITLE
Get current locale

### ISSUE THREAD

**Issue by cloetensbrecht** [rmdort/react-redux-multilingual#23]
How can we catch the current locale?
Can you add an example to the readme?

**Comment by dhoncrisley** [comment]
I search on the code but have no way to get, like a function. You can get the current locale with the getState function in the "Intl" reducer.
like ```store.getState().Intl.locale```

**Comment by rmdort** [comment]
This may help - https://github.com/rmdort/react-redux-multilingual/issues/4
