### ISSUE TITLE
I want to set default locale for module

### ISSUE THREAD

**Issue by tandm160797** [rmdort/react-redux-multilingual#25]
![image](https://user-images.githubusercontent.com/75089753/118800543-3a8a9f80-b8ca-11eb-8a0a-fabafb69bc46.png)

In my code, line 16.
I set to props locale="zh" but it don't work because author don't handle this case, and author set initialState for locale is "en"
Can you help handle this case?
I come from Vietnam, my english is bad. hihi
Thanks.

**Comment by rmdort** [comment]
Hi, You have to set initial state when you are creating the store. 

https://github.com/rmdort/react-redux-multilingual#setting-the-initial-locale

**Comment by tandm160797** [comment]
> https://github.com/rmdort/react-redux-multilingual#setting-the-initial-locale

I get it, thank you very much.
I'm not an redux expert before
