### ISSUE TITLE
ES6 - IntlActions.setLocale

### ISSUE THREAD

**Issue by marcus-sa** [rmdort/react-redux-multilingual#7]
When I read the README.md I noticed that there's a missing option on how to set which translation to be used.
Then later on I read some of the source code, and then noticed there's a redux action called **setLocale** which gets exported as **IntlActions.setLocale**

I'm currently using the script below, and by default the local language is set to **en**, but whenever I try to set the local to let's say **zh** it's still hasn't changed.

**translations.js**
```
import { IntlActions } from 'react-redux-multilingual'

import Preferences from '../preferences'
import HTTP from './utils/http'
import {APP} from '../config'

export default function (callback: Function) {
  Preferences.get('language', (iso) => {
    IntlActions.setLocale(iso)
    HTTP.get(`${APP.API}/translations`, callback)
  })
}
```
**index.js**
```
import React from 'react'
import createBrowserHistory from 'history/createBrowserHistory'
import { MemoryRouter as Router } from 'react-router-dom'
import { IntlReducer as Intl, IntlProvider } from 'react-redux-multilingual'
import { createStore, combineReducers } from 'redux'
import { Provider } from 'react-redux'

import App from './utils/app'
import Routes from './routes'
import getTranslations from './translations'

const history = createBrowserHistory()

const reducers = combineReducers(Object.assign({}, { Intl }))
const store = createStore(reducers)

getTranslations(translations => {
  App.init(
    <Provider store={store}>
      <IntlProvider translations={translations}>
        <Router history={history}>
          <Routes />
        </Router>
      </IntlProvider>
    </Provider>,
    '#content-wrapper'
  )
})
```

**Comment by marcus-sa** [comment]
I torn apart the package, removed everything related to **redux**, and decided to use it myself instead of waiting for this issue to be fixed.

```<IntlProvider ... locale={locale}>``` didn't work when **redux** was there.

**Comment by rmdort** [comment]
Yes. All you have to do is add `locale` prop to `IntlProvider`

````
<IntlProvider translations={translations} locale='en'>
</IntlProvider>
````

**Comment by marcus-sa** [comment]
Already tried, that didn't work, as written above.
I don't use **Redux** for my application anyway, so that is just a whole bunch of useless code.

If you create another git repository I can PR what I have, so that people without **Redux** can use it properly.

**Comment by rmdort** [comment]
Thanks. But this library is only meant to be used with redux. You can share the link to your library which doesn't have redux dependency and i can add it to Readme.
