### ISSUE TITLE
Unnecessary base language messages

### ISSUE THREAD

**Issue by divined** [rmdort/react-redux-multilingual#8]
```
{
  en: {
    locale: 'en-US',
    messages: {
      'Some english string': 'Some english string'                 //**ablle to miss this?**
    }
  },
  de: {
    locale: 'de-DE',
    messages: {
      'Some english string': 'Some translated to de string'
    }
  }
}
```

**Comment by rmdort** [comment]
Please explain your issue in detail

**Comment by TomOffringa** [comment]
@rmdort I think @divined means that it's neccessary to define the base language as well. If you have a base locale of English, you still have to add the English translations of English language strings as well. Instead of not translating the base locale.

**Comment by rmdort** [comment]
You don't have to use base language. You can set the initialstate of the 'Intl' reducer to have 'locale:de'
