### ISSUE TITLE
I can't set locale='ru' by default

### ISSUE THREAD

**Issue by JuliaPetrishina** [rmdort/react-redux-multilingual#9]
I can't set locale='ru' by default. Could you help me with this?

**Comment by rmdort** [comment]
You can set default locale by passing locale prop to IntlProvider

````
<IntlProvider locale='ru'>
</IntlProvider >
````

Or you can dispatch an action

````
import { IntlActions } from 'react-redux-multilingual'

const store =createStore(....)
store.dispatch(IntlActions.setLocale('ru'))
````

**Comment by JuliaPetrishina** [comment]
@rmdort 
The second one helped. Thanks a lot!

**Comment by rmdort** [comment]
ok great. I have added this to the Readme.
